### ISSUE TITLE
Difference from website.

### ISSUE THREAD

**Issue by mesqueeb** [dharmaprotocol/WhitePaper#2]
There is a difference with this readme and the website:
  
<img width="830" alt="2018-03-08 18 07 23" src="https://user-images.githubusercontent.com/3253920/37142510-a48e28c4-22fb-11e8-970a-349def6ba687.png">

The part underneath **Contracts** doesn't exist on the readme...

Also this part has a Typo which I wanted to report: `prtocol mechanics.` (the final 2 words)

**Comment by mesqueeb** [comment]
Also strange CSS bug where the sentence first words start sometimes on top of the previous sentence last letter...

**Comment by nadavhollander** [comment]
Good catch, thanks for pointing out.  Fixing discrepancy.

**Comment by mesqueeb** [comment]
@nadavhollander 
The word `prtocol's mechanics` is still there. I believe it's `protocol's`?
